[2025-04-07T03:44:34.100+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sparkStreaming_dag.pyspark_consumer manual__2025-04-07T03:39:31.238411+00:00 [queued]>
[2025-04-07T03:44:34.113+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sparkStreaming_dag.pyspark_consumer manual__2025-04-07T03:39:31.238411+00:00 [queued]>
[2025-04-07T03:44:34.113+0000] {taskinstance.py:1361} INFO - Starting attempt 2 of 2
[2025-04-07T03:44:34.130+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): pyspark_consumer> on 2025-04-07 03:39:31.238411+00:00
[2025-04-07T03:44:34.138+0000] {standard_task_runner.py:57} INFO - Started process 84105 to run task
[2025-04-07T03:44:34.141+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'sparkStreaming_dag', 'pyspark_consumer', 'manual__2025-04-07T03:39:31.238411+00:00', '--job-id', '218', '--raw', '--subdir', 'DAGS_FOLDER/dag_sparkStreamJob.py', '--cfg-path', '/tmp/tmpwa6cp8kw']
[2025-04-07T03:44:34.144+0000] {standard_task_runner.py:85} INFO - Job 218: Subtask pyspark_consumer
[2025-04-07T03:44:34.198+0000] {task_command.py:416} INFO - Running <TaskInstance: sparkStreaming_dag.pyspark_consumer manual__2025-04-07T03:39:31.238411+00:00 [running]> on host a6934a850e84
[2025-04-07T03:44:34.293+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sparkStreaming_dag' AIRFLOW_CTX_TASK_ID='pyspark_consumer' AIRFLOW_CTX_EXECUTION_DATE='2025-04-07T03:39:31.238411+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-07T03:39:31.238411+00:00'
[2025-04-07T03:44:34.295+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-04-07T03:44:34.295+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'docker exec spark-server ./spark/bin/spark-submit --packages org.apache.spark:spark-sql-kafka-0-10_2.12:3.3.2 ./kafkaToDelta.py &&                 echo "spark-submit completed." &&         ']
[2025-04-07T03:44:34.313+0000] {subprocess.py:86} INFO - Output:
[2025-04-07T03:44:34.315+0000] {subprocess.py:93} INFO - /bin/bash: -c: line 2: syntax error: unexpected end of file
[2025-04-07T03:44:34.315+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2025-04-07T03:44:34.331+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2025-04-07T03:44:34.335+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=sparkStreaming_dag, task_id=pyspark_consumer, execution_date=20250407T033931, start_date=20250407T034434, end_date=20250407T034434
[2025-04-07T03:44:34.352+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 218 for task pyspark_consumer (Bash command failed. The command returned a non-zero exit code 2.; 84105)
[2025-04-07T03:44:34.399+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-04-07T03:44:34.420+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
