[2025-03-30T14:40:01.222+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: kafka_spark_dag.kafka_data_stream scheduled__2025-03-30T14:30:00+00:00 [queued]>
[2025-03-30T14:40:01.229+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: kafka_spark_dag.kafka_data_stream scheduled__2025-03-30T14:30:00+00:00 [queued]>
[2025-03-30T14:40:01.230+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2025-03-30T14:40:01.240+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): kafka_data_stream> on 2025-03-30 14:30:00+00:00
[2025-03-30T14:40:01.246+0000] {standard_task_runner.py:57} INFO - Started process 32738 to run task
[2025-03-30T14:40:01.249+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'kafka_spark_dag', 'kafka_data_stream', 'scheduled__2025-03-30T14:30:00+00:00', '--job-id', '144', '--raw', '--subdir', 'DAGS_FOLDER/dag_kafka_spark.py', '--cfg-path', '/tmp/tmpz8aj79hy']
[2025-03-30T14:40:01.252+0000] {standard_task_runner.py:85} INFO - Job 144: Subtask kafka_data_stream
[2025-03-30T14:40:01.300+0000] {task_command.py:416} INFO - Running <TaskInstance: kafka_spark_dag.kafka_data_stream scheduled__2025-03-30T14:30:00+00:00 [running]> on host a6934a850e84
[2025-03-30T14:40:01.389+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='kafka_spark_dag' AIRFLOW_CTX_TASK_ID='kafka_data_stream' AIRFLOW_CTX_EXECUTION_DATE='2025-03-30T14:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-30T14:30:00+00:00'
[2025-03-30T14:40:01.392+0000] {kafka_producer_util.py:30} INFO - Attempting to use KafkaProducer class: <class 'kafka.producer.kafka.KafkaProducer'>
[2025-03-30T14:40:01.392+0000] {kafka_producer_util.py:31} INFO - Imported from module: kafka.producer.kafka
[2025-03-30T14:40:01.393+0000] {kafka_producer_util.py:34} INFO - Top-level kafka module path: /home/***/.local/lib/python3.8/site-packages/kafka/__init__.py
[2025-03-30T14:40:01.396+0000] {conn.py:380} INFO - <BrokerConnection node_id=bootstrap-0 host=kafka-server:9092 <connecting> [IPv4 ('172.20.0.5', 9092)]>: connecting to kafka-server:9092 [('172.20.0.5', 9092) IPv4]
[2025-03-30T14:40:01.397+0000] {conn.py:1205} INFO - Probing node bootstrap-0 broker version
[2025-03-30T14:40:01.400+0000] {conn.py:410} INFO - <BrokerConnection node_id=bootstrap-0 host=kafka-server:9092 <connecting> [IPv4 ('172.20.0.5', 9092)]>: Connection complete.
[2025-03-30T14:40:01.504+0000] {conn.py:1267} INFO - Broker version identified as 2.5.0
[2025-03-30T14:40:01.504+0000] {conn.py:1268} INFO - Set configuration api_version=(2, 5, 0) to skip auto check_version requests on startup
[2025-03-30T14:40:01.507+0000] {kafka_producer_util.py:48} INFO - KafkaProducer instantiated successfully.
[2025-03-30T14:40:01.512+0000] {api_data_collector.py:47} ERROR - API Request Error: HTTPConnectionPool(host='127.0.0.1', port=8000): Max retries exceeded with url: /v2/random-data-list (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa265fd7c70>: Failed to establish a new connection: [Errno 111] Connection refused'))
[2025-03-30T14:40:01.513+0000] {kafka.py:483} INFO - Closing the Kafka producer with 9223372036.0 secs timeout.
[2025-03-30T14:40:01.514+0000] {conn.py:919} INFO - <BrokerConnection node_id=bootstrap-0 host=kafka-server:9092 <connected> [IPv4 ('172.20.0.5', 9092)]>: Closing connection. 
[2025-03-30T14:40:01.515+0000] {python.py:194} INFO - Done. Returned value was: None
[2025-03-30T14:40:01.525+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=kafka_spark_dag, task_id=kafka_data_stream, execution_date=20250330T143000, start_date=20250330T144001, end_date=20250330T144001
[2025-03-30T14:40:01.548+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-03-30T14:40:01.572+0000] {taskinstance.py:2778} INFO - 1 downstream tasks scheduled from follow-on schedule check
